using System.Collections.Generic;
using System.Data.SqlClient;
using Dapper;
using Sistema.DUE.Web.Config;
using Sistema.DUE.Web.Models;

namespace Sistema.DUE.Web.DAO
{
    public class PaisesDAO
    {
        public IEnumerable<Pais> ObterPaises()
        {
            using (SqlConnection con = new SqlConnection(Banco.StringConexao()))
            {
                return con.Query<Pais>(@"SELECT Id, Descricao, Sigla FROM [dbo].[Tb_Paises] ORDER BY Descricao");
            }
        }

        public static IEnumerable<Pais> ObterPaisesSiscomex()
        {
            var lista = new List<Pais>();

            lista.Add(new Pais(994, "A DESIGNAR - ", ""));
            lista.Add(new Pais(13, "AFEGANISTAO - AF", "AF"));
            lista.Add(new Pais(756, "AFRICA DO SUL - ZA", "ZA"));
            lista.Add(new Pais(15, "ALAND, ILHAS - AX", "AX"));
            lista.Add(new Pais(17, "ALBANIA, REPUBLICA DA - AL", "AL"));
            lista.Add(new Pais(23, "ALEMANHA - DE", "DE"));
            lista.Add(new Pais(37, "ANDORRA - AD", "AD"));
            lista.Add(new Pais(40, "ANGOLA - AO", "AO"));
            lista.Add(new Pais(41, "ANGUILLA - AI", "AI"));
            lista.Add(new Pais(43, "ANTIGUA E BARBUDA - AG", "AG"));
            lista.Add(new Pais(42, "ANTÁRTICA - AQ", "AQ"));
            lista.Add(new Pais(53, "ARABIA SAUDITA - SA", "SA"));
            lista.Add(new Pais(59, "ARGELIA - DZ", "DZ"));
            lista.Add(new Pais(63, "ARGENTINA - AR", "AR"));
            lista.Add(new Pais(64, "ARMENIA, REPUBLICA DA - AM", "AM"));
            lista.Add(new Pais(65, "ARUBA - AW", "AW"));
            lista.Add(new Pais(69, "AUSTRALIA - AU", "AU"));
            lista.Add(new Pais(72, "AUSTRIA - AT", "AT"));
            lista.Add(new Pais(73, "AZERBAIJAO, REPUBLICA DO - AZ", "AZ"));
            lista.Add(new Pais(77, "BAHAMAS, ILHAS - BS", "BS"));
            lista.Add(new Pais(80, "BAHREIN, ILHAS - BH", "BH"));
            lista.Add(new Pais(995, "BANCOS CENTRAIS - ", ""));
            lista.Add(new Pais(81, "BANGLADESH - BD", "BD"));
            lista.Add(new Pais(83, "BARBADOS - BB", "BB"));
            lista.Add(new Pais(85, "BELARUS, REPUBLICA DA - BY", "BY"));
            lista.Add(new Pais(87, "BELGICA - BE", "BE"));
            lista.Add(new Pais(88, "BELIZE - BZ", "BZ"));
            lista.Add(new Pais(229, "BENIN - BJ", "BJ"));
            lista.Add(new Pais(90, "BERMUDAS - BM", "BM"));
            lista.Add(new Pais(97, "BOLIVIA, ESTADO PLURINACIONAL DA - BO", "BO"));
            lista.Add(new Pais(99, "BONAIRE, SAINT EUSTATIUS E SABA - BQ", "BQ"));
            lista.Add(new Pais(98, "BOSNIA-HERZEGOVINA (REPUBLICA DA) - BA", "BA"));
            lista.Add(new Pais(101, "BOTSUANA - BW", "BW"));
            lista.Add(new Pais(102, "BOUVET, ILHA - BV", "BV"));
            lista.Add(new Pais(105, "BRASIL - BR", "BR"));
            lista.Add(new Pais(108, "BRUNEI - BN", "BN"));
            lista.Add(new Pais(111, "BULGARIA, REPUBLICA DA - BG", "BG"));
            lista.Add(new Pais(31, "BURKINA FASO - BF", "BF"));
            lista.Add(new Pais(115, "BURUNDI - BI", "BI"));
            lista.Add(new Pais(119, "BUTAO - BT", "BT"));
            lista.Add(new Pais(127, "CABO VERDE, REPUBLICA DE - CV", "CV"));
            lista.Add(new Pais(145, "CAMAROES - CM", "CM"));
            lista.Add(new Pais(141, "CAMBOJA - KH", "KH"));
            lista.Add(new Pais(149, "CANADA - CA", "CA"));
            lista.Add(new Pais(154, "CATAR - QA", "QA"));
            lista.Add(new Pais(137, "CAYMAN, ILHAS - KY", "KY"));
            lista.Add(new Pais(153, "CAZAQUISTAO, REPUBLICA DO - KZ", "KZ"));
            lista.Add(new Pais(788, "CHADE - TD", "TD"));
            lista.Add(new Pais(158, "CHILE - CL", "CL"));
            lista.Add(new Pais(160, "CHINA, REPUBLICA POPULAR - CN", "CN"));
            lista.Add(new Pais(163, "CHIPRE - CY", "CY"));
            lista.Add(new Pais(511, "CHRISTMAS,ILHA (NAVIDAD) - CX", "CX"));
            lista.Add(new Pais(741, "CINGAPURA - SG", "SG"));
            lista.Add(new Pais(165, "COCOS(KEELING),ILHAS - CC", "CC"));
            lista.Add(new Pais(169, "COLOMBIA - CO", "CO"));
            lista.Add(new Pais(173, "COMORES, ILHAS - KM", "KM"));
            lista.Add(new Pais(177, "CONGO - CG", "CG"));
            lista.Add(new Pais(888, "CONGO, REPUBLICA DEMOCRATICA DO - CD", "CD"));
            lista.Add(new Pais(183, "COOK, ILHAS - CK", "CK"));
            lista.Add(new Pais(187, "COREIA (DO NORTE), REP.POP.DEMOCRATICA - KP", "KP"));
            lista.Add(new Pais(190, "COREIA (DO SUL), REPUBLICA DA - KR", "KR"));
            lista.Add(new Pais(193, "COSTA DO MARFIM - CI", "CI"));
            lista.Add(new Pais(196, "COSTA RICA - CR", "CR"));
            lista.Add(new Pais(195, "CROACIA (REPUBLICA DA) - HR", "HR"));
            lista.Add(new Pais(199, "CUBA - CU", "CU"));
            lista.Add(new Pais(200, "CURACAO - CW", "CW"));
            lista.Add(new Pais(232, "DINAMARCA - DK", "DK"));
            lista.Add(new Pais(783, "DJIBUTI - DJ", "DJ"));
            lista.Add(new Pais(235, "DOMINICA,ILHA - DM", "DM"));
            lista.Add(new Pais(240, "EGITO - EG", "EG"));
            lista.Add(new Pais(687, "EL SALVADOR - SV", "SV"));
            lista.Add(new Pais(244, "EMIRADOS ARABES UNIDOS - AE", "AE"));
            lista.Add(new Pais(239, "EQUADOR - EC", "EC"));
            lista.Add(new Pais(243, "ERITREIA - ER", "ER"));
            lista.Add(new Pais(247, "ESLOVACA, REPUBLICA - SK", "SK"));
            lista.Add(new Pais(246, "ESLOVENIA, REPUBLICA DA - SI", "SI"));
            lista.Add(new Pais(245, "ESPANHA - ES", "ES"));
            lista.Add(new Pais(754, "ESSUATINI - SZ", "SZ"));
            lista.Add(new Pais(249, "ESTADOS UNIDOS - US", "US"));
            lista.Add(new Pais(251, "ESTONIA, REPUBLICA DA - EE", "EE"));
            lista.Add(new Pais(253, "ETIOPIA - ET", "ET"));
            lista.Add(new Pais(255, "FALKLAND (ILHAS MALVINAS) - FK", "FK"));
            lista.Add(new Pais(259, "FEROE, ILHAS - FO", "FO"));
            lista.Add(new Pais(870, "FIJI - FJ", "FJ"));
            lista.Add(new Pais(267, "FILIPINAS - PH", "PH"));
            lista.Add(new Pais(271, "FINLANDIA - FI", "FI"));
            lista.Add(new Pais(161, "FORMOSA (TAIWAN) - TW", "TW"));
            lista.Add(new Pais(275, "FRANCA - FR", "FR"));
            lista.Add(new Pais(281, "GABAO - GA", "GA"));
            lista.Add(new Pais(285, "GAMBIA - GM", "GM"));
            lista.Add(new Pais(289, "GANA - GH", "GH"));
            lista.Add(new Pais(291, "GEORGIA, REPUBLICA DA - GE", "GE"));
            lista.Add(new Pais(292, "GEÓRGIA DO SUL E SANDWICH DO SUL, ILHAS - GS", "GS"));
            lista.Add(new Pais(293, "GIBRALTAR - GI", "GI"));
            lista.Add(new Pais(297, "GRANADA - GD", "GD"));
            lista.Add(new Pais(301, "GRECIA - GR", "GR"));
            lista.Add(new Pais(305, "GROENLANDIA - GL", "GL"));
            lista.Add(new Pais(309, "GUADALUPE - GP", "GP"));
            lista.Add(new Pais(313, "GUAM - GU", "GU"));
            lista.Add(new Pais(317, "GUATEMALA - GT", "GT"));
            lista.Add(new Pais(321, "GUERNSEY - GG", "GG"));
            lista.Add(new Pais(337, "GUIANA - GY", "GY"));
            lista.Add(new Pais(325, "GUIANA FRANCESA - GF", "GF"));
            lista.Add(new Pais(329, "GUINE - GN", "GN"));
            lista.Add(new Pais(334, "GUINE-BISSAU - GW", "GW"));
            lista.Add(new Pais(331, "GUINE-EQUATORIAL - GQ", "GQ"));
            lista.Add(new Pais(341, "HAITI - HT", "HT"));
            lista.Add(new Pais(343, "HEARD E ILHAS MCDONALD, ILHA - HM", "HM"));
            lista.Add(new Pais(345, "HONDURAS - HN", "HN"));
            lista.Add(new Pais(351, "HONG KONG - HK", "HK"));
            lista.Add(new Pais(355, "HUNGRIA, REPUBLICA DA - HU", "HU"));
            lista.Add(new Pais(357, "IEMEN - YE", "YE"));
            lista.Add(new Pais(361, "INDIA - IN", "IN"));
            lista.Add(new Pais(365, "INDONESIA - ID", "ID"));
            lista.Add(new Pais(372, "IRA, REPUBLICA ISLAMICA DO - IR", "IR"));
            lista.Add(new Pais(369, "IRAQUE - IQ", "IQ"));
            lista.Add(new Pais(375, "IRLANDA - IE", "IE"));
            lista.Add(new Pais(379, "ISLANDIA - IS", "IS"));
            lista.Add(new Pais(383, "ISRAEL - IL", "IL"));
            lista.Add(new Pais(386, "ITALIA - IT", "IT"));
            lista.Add(new Pais(391, "JAMAICA - JM", "JM"));
            lista.Add(new Pais(399, "JAPAO - JP", "JP"));
            lista.Add(new Pais(393, "JERSEY - JE", "JE"));
            lista.Add(new Pais(403, "JORDANIA - JO", "JO"));
            lista.Add(new Pais(411, "KIRIBATI - KI", "KI"));
            lista.Add(new Pais(198, "KUWAIT - KW", "KW"));
            lista.Add(new Pais(420, "LAOS, REP.POP.DEMOCR.DO - LA", "LA"));
            lista.Add(new Pais(426, "LESOTO - LS", "LS"));
            lista.Add(new Pais(427, "LETONIA, REPUBLICA DA - LV", "LV"));
            lista.Add(new Pais(431, "LIBANO - LB", "LB"));
            lista.Add(new Pais(434, "LIBERIA - LR", "LR"));
            lista.Add(new Pais(438, "LIBIA - LY", "LY"));
            lista.Add(new Pais(440, "LIECHTENSTEIN - LI", "LI"));
            lista.Add(new Pais(442, "LITUANIA, REPUBLICA DA - LT", "LT"));
            lista.Add(new Pais(445, "LUXEMBURGO - LU", "LU"));
            lista.Add(new Pais(447, "MACAU - MO", "MO"));
            lista.Add(new Pais(449, "MACEDONIA DO NORTE - MK", "MK"));
            lista.Add(new Pais(450, "MADAGASCAR - MG", "MG"));
            lista.Add(new Pais(455, "MALASIA - MY", "MY"));
            lista.Add(new Pais(458, "MALAVI - MW", "MW"));
            lista.Add(new Pais(461, "MALDIVAS - MV", "MV"));
            lista.Add(new Pais(464, "MALI - ML", "ML"));
            lista.Add(new Pais(467, "MALTA - MT", "MT"));
            lista.Add(new Pais(359, "MAN, ILHA DE - IM", "IM"));
            lista.Add(new Pais(472, "MARIANAS DO NORTE - MP", "MP"));
            lista.Add(new Pais(474, "MARROCOS - MA", "MA"));
            lista.Add(new Pais(476, "MARSHALL,ILHAS - MH", "MH"));
            lista.Add(new Pais(477, "MARTINICA - MQ", "MQ"));
            lista.Add(new Pais(485, "MAURICIO - MU", "MU"));
            lista.Add(new Pais(488, "MAURITANIA - MR", "MR"));
            lista.Add(new Pais(489, "MAYOTTE - YT", "YT"));
            lista.Add(new Pais(493, "MEXICO - MX", "MX"));
            lista.Add(new Pais(93, "MIANMAR (BIRMANIA) - MM", "MM"));
            lista.Add(new Pais(499, "MICRONESIA - FM", "FM"));
            lista.Add(new Pais(505, "MOCAMBIQUE - MZ", "MZ"));
            lista.Add(new Pais(494, "MOLDAVIA, REPUBLICA DA - MD", "MD"));
            lista.Add(new Pais(495, "MONACO - MC", "MC"));
            lista.Add(new Pais(497, "MONGOLIA - MN", "MN"));
            lista.Add(new Pais(498, "MONTENEGRO - ME", "ME"));
            lista.Add(new Pais(501, "MONTSERRAT,ILHAS - MS", "MS"));
            lista.Add(new Pais(507, "NAMIBIA - NA", "NA"));
            lista.Add(new Pais(508, "NAURU - NR", "NR"));
            lista.Add(new Pais(517, "NEPAL - NP", "NP"));
            lista.Add(new Pais(521, "NICARAGUA - NI", "NI"));
            lista.Add(new Pais(525, "NIGER - NE", "NE"));
            lista.Add(new Pais(528, "NIGERIA - NG", "NG"));
            lista.Add(new Pais(531, "NIUE,ILHA - NU", "NU"));
            lista.Add(new Pais(535, "NORFOLK,ILHA - NF", "NF"));
            lista.Add(new Pais(538, "NORUEGA - NO", "NO"));
            lista.Add(new Pais(542, "NOVA CALEDONIA - NC", "NC"));
            lista.Add(new Pais(548, "NOVA ZELANDIA - NZ", "NZ"));
            lista.Add(new Pais(556, "OMA - OM", "OM"));
            lista.Add(new Pais(997, "ORGANIZACOES INTERNACIONAIS - ", ""));
            lista.Add(new Pais(566, "PACIFICO,ILHAS DO (POSSESSAO DOS EUA) - UM", "UM"));
            lista.Add(new Pais(573, "PAISES BAIXOS (HOLANDA) - NL", "NL"));
            lista.Add(new Pais(575, "PALAU - PW", "PW"));
            lista.Add(new Pais(578, "PALESTINA - PS", "PS"));
            lista.Add(new Pais(580, "PANAMA - PA", "PA"));
            lista.Add(new Pais(545, "PAPUA NOVA GUINE - PG", "PG"));
            lista.Add(new Pais(576, "PAQUISTAO - PK", "PK"));
            lista.Add(new Pais(586, "PARAGUAI - PY", "PY"));
            lista.Add(new Pais(589, "PERU - PE", "PE"));
            lista.Add(new Pais(593, "PITCAIRN,ILHA - PN", "PN"));
            lista.Add(new Pais(599, "POLINESIA FRANCESA - PF", "PF"));
            lista.Add(new Pais(603, "POLONIA, REPUBLICA DA - PL", "PL"));
            lista.Add(new Pais(611, "PORTO RICO - PR", "PR"));
            lista.Add(new Pais(607, "PORTUGAL - PT", "PT"));
            lista.Add(new Pais(990, "PROVISAO DE NAVIOS E AERONAVES - ", ""));
            lista.Add(new Pais(623, "QUENIA - KE", "KE"));
            lista.Add(new Pais(625, "QUIRGUIZ, REPUBLICA - KG", "KG"));
            lista.Add(new Pais(628, "REINO UNIDO - GB", "GB"));
            lista.Add(new Pais(640, "REPUBLICA CENTRO-AFRICANA - CF", "CF"));
            lista.Add(new Pais(647, "REPUBLICA DOMINICANA - DO", "DO"));
            lista.Add(new Pais(660, "REUNIAO, ILHA - RE", "RE"));
            lista.Add(new Pais(670, "ROMENIA - RO", "RO"));
            lista.Add(new Pais(675, "RUANDA - RW", "RW"));
            lista.Add(new Pais(676, "RUSSIA, FEDERACAO DA - RU", "RU"));
            lista.Add(new Pais(685, "SAARA OCIDENTAL - EH", "EH"));
            lista.Add(new Pais(677, "SALOMAO, ILHAS - SB", "SB"));
            lista.Add(new Pais(690, "SAMOA - WS", "WS"));
            lista.Add(new Pais(691, "SAMOA AMERICANA - AS", "AS"));
            lista.Add(new Pais(697, "SAN MARINO - SM", "SM"));
            lista.Add(new Pais(710, "SANTA HELENA - SH", "SH"));
            lista.Add(new Pais(715, "SANTA LUCIA - LC", "LC"));
            lista.Add(new Pais(693, "SAO BARTOLOMEU - BL", "BL"));
            lista.Add(new Pais(695, "SAO CRISTOVAO E NEVES,ILHAS - KN", "KN"));
            lista.Add(new Pais(700, "SAO PEDRO E MIQUELON - PM", "PM"));
            lista.Add(new Pais(720, "SAO TOME E PRINCIPE, ILHAS - ST", "ST"));
            lista.Add(new Pais(705, "SAO VICENTE E GRANADINAS - VC", "VC"));
            lista.Add(new Pais(728, "SENEGAL - SN", "SN"));
            lista.Add(new Pais(735, "SERRA LEOA - SL", "SL"));
            lista.Add(new Pais(737, "SERVIA - RS", "RS"));
            lista.Add(new Pais(731, "SEYCHELLES - SC", "SC"));
            lista.Add(new Pais(744, "SIRIA, REPUBLICA ARABE DA - SY", "SY"));
            lista.Add(new Pais(748, "SOMALIA - SO", "SO"));
            lista.Add(new Pais(750, "SRI LANKA - LK", "LK"));
            lista.Add(new Pais(759, "SUDAO - SD", "SD"));
            lista.Add(new Pais(760, "SUDAO DO SUL - SS", "SS"));
            lista.Add(new Pais(764, "SUECIA - SE", "SE"));
            lista.Add(new Pais(767, "SUICA - CH", "CH"));
            lista.Add(new Pais(770, "SURINAME - SR", "SR"));
            lista.Add(new Pais(755, "SVALBARD E JAN MAYEN - SJ", "SJ"));
            lista.Add(new Pais(698, "SÃO MARTINHO, ILHA DE (PARTE FRANCESA) - MF", "MF"));
            lista.Add(new Pais(699, "SÃO MARTINHO, ILHA DE (PARTE HOLANDESA) - SX", "SX"));
            lista.Add(new Pais(772, "TADJIQUISTAO, REPUBLICA DO - TJ", "TJ"));
            lista.Add(new Pais(776, "TAILANDIA - TH", "TH"));
            lista.Add(new Pais(780, "TANZANIA, REP.UNIDA DA - TZ", "TZ"));
            lista.Add(new Pais(791, "TCHECA, REPUBLICA - CZ", "CZ"));
            lista.Add(new Pais(781, "TERRAS AUSTRAIS FRANCESAS - TF", "TF"));
            lista.Add(new Pais(782, "TERRITORIO BRIT.OC.INDICO - IO", "IO"));
            lista.Add(new Pais(795, "TIMOR LESTE - TL", "TL"));
            lista.Add(new Pais(800, "TOGO - TG", "TG"));
            lista.Add(new Pais(810, "TONGA - TO", "TO"));
            lista.Add(new Pais(805, "TOQUELAU,ILHAS - TK", "TK"));
            lista.Add(new Pais(815, "TRINIDAD E TOBAGO - TT", "TT"));
            lista.Add(new Pais(820, "TUNISIA - TN", "TN"));
            lista.Add(new Pais(823, "TURCAS E CAICOS,ILHAS - TC", "TC"));
            lista.Add(new Pais(824, "TURCOMENISTAO, REPUBLICA DO - TM", "TM"));
            lista.Add(new Pais(827, "TURQUIA - TR", "TR"));
            lista.Add(new Pais(828, "TUVALU - TV", "TV"));
            lista.Add(new Pais(831, "UCRANIA - UA", "UA"));
            lista.Add(new Pais(833, "UGANDA - UG", "UG"));
            lista.Add(new Pais(845, "URUGUAI - UY", "UY"));
            lista.Add(new Pais(847, "UZBEQUISTAO, REPUBLICA DO - UZ", "UZ"));
            lista.Add(new Pais(551, "VANUATU - VU", "VU"));
            lista.Add(new Pais(848, "VATICANO, EST.DA CIDADE DO - VA", "VA"));
            lista.Add(new Pais(850, "VENEZUELA - VE", "VE"));
            lista.Add(new Pais(858, "VIETNA - VN", "VN"));
            lista.Add(new Pais(863, "VIRGENS,ILHAS (BRITANICAS) - VG", "VG"));
            lista.Add(new Pais(866, "VIRGENS,ILHAS (E.U.A.) - VI", "VI"));
            lista.Add(new Pais(875, "WALLIS E FUTUNA, ILHAS - WF", ""));
            lista.Add(new Pais(875, "WALLIS E FUTUNA, ILHAS - WF", ""));
            lista.Add(new Pais(890, "ZAMBIA - ZM", "ZM"));
            lista.Add(new Pais(665, "ZIMBABUE - ZW", "ZW"));

            return lista;
        }

        public static IEnumerable<PaisesDanfe> ObterPaisesDanfe()
        {
            var lista = new List<PaisesDanfe>();

            lista.Add(new PaisesDanfe("0132", "Afeganistão", "013", "AF", "AFG"));
            lista.Add(new PaisesDanfe("7560", "África do Sul", "756", "ZA", "ZAF"));
            lista.Add(new PaisesDanfe("0175", "Albânia", "017", "AL", "ALB"));
            lista.Add(new PaisesDanfe("0230", "Alemanha", "023", "DE", "DEU"));
            lista.Add(new PaisesDanfe("0370", "Andorra", "037", "AD", "AND"));
            lista.Add(new PaisesDanfe("0400", "Angola", "040", "AO", "AGO"));
            lista.Add(new PaisesDanfe("0418", "Anguilla", "041", "AI", "AIA"));
            lista.Add(new PaisesDanfe("0434", "Antígua e Barbuda", "043", "AG", "ATG"));
            lista.Add(new PaisesDanfe("0477", "Antilhas Holandesas", "047", "AN", "ANT"));
            lista.Add(new PaisesDanfe("0531", "Arábia Saudita", "053", "SA", "SAU"));
            lista.Add(new PaisesDanfe("0590", "Argélia", "059", "DZ", "DZA"));
            lista.Add(new PaisesDanfe("0639", "Argentina", "063", "AR", "ARG"));
            lista.Add(new PaisesDanfe("0647", "Armênia", "064", "AM", "ARM"));
            lista.Add(new PaisesDanfe("0655", "Aruba", "065", "AW", "ABW"));
            lista.Add(new PaisesDanfe("0698", "Austrália", "069", "AU", "AUS"));
            lista.Add(new PaisesDanfe("0728", "Áustria", "072", "AT", "AUT"));
            lista.Add(new PaisesDanfe("0736", "Azerbaijão", "073", "AZ", "AZE"));
            lista.Add(new PaisesDanfe("0779", "Bahamas", "077", "BS", "BHS"));
            lista.Add(new PaisesDanfe("0817", "Bangladesh", "081", "BD", "BGD"));
            lista.Add(new PaisesDanfe("0833", "Barbados", "083", "BB", "BRB"));
            lista.Add(new PaisesDanfe("0809", "Bahrein", "080", "BH", "BHR"));
            lista.Add(new PaisesDanfe("0850", "Belarus", "085", "BY", "BLR"));
            lista.Add(new PaisesDanfe("0876", "Bélgica", "087", "BE", "BEL"));
            lista.Add(new PaisesDanfe("0884", "Belize", "088", "BZ", "BLZ"));
            lista.Add(new PaisesDanfe("2291", "Benin", "229", "BJ", "BEN"));
            lista.Add(new PaisesDanfe("0906", "Bermudas", "090", "BM", "BMU"));
            lista.Add(new PaisesDanfe("0973", "Bolívia", "097", "BO", "BOL"));
            lista.Add(new PaisesDanfe("0990", "Bonaires, Saint Eustatius e Saba", "099", "BQ", "BES"));
            lista.Add(new PaisesDanfe("0981", "Bósnia-Herzegovina", "098", "BA", "BIH"));
            lista.Add(new PaisesDanfe("1015", "Botsuana", "101", "BW", "BWA"));
            lista.Add(new PaisesDanfe("1098", "Bouvet, Ilha", "102", "BV", "BVT"));
            lista.Add(new PaisesDanfe("1058", "Brasil", "105", "BR", "BRA"));
            lista.Add(new PaisesDanfe("1082", "Brunei", "108", "BN", "BRN"));
            lista.Add(new PaisesDanfe("1112", "Bulgária", "111", "BG", "BGR"));
            lista.Add(new PaisesDanfe("0310", "Burkina Faso", "031", "BF", "BFA"));
            lista.Add(new PaisesDanfe("1155", "Burundi", "115", "BI", "BDI"));
            lista.Add(new PaisesDanfe("1198", "Butão", "119", "BT", "BTN"));
            lista.Add(new PaisesDanfe("1279", "Cabo Verde", "127", "CV", "CPV"));
            lista.Add(new PaisesDanfe("1457", "Camarões", "145", "CM", "CMR"));
            lista.Add(new PaisesDanfe("1414", "Camboja", "141", "KH", "KHM"));
            lista.Add(new PaisesDanfe("1490", "Canadá", "149", "CA", "CAN"));
            lista.Add(new PaisesDanfe("1511", "Canárias, Ilhas", "151", "ES", "ESP"));
            lista.Add(new PaisesDanfe("1546", "Catar", "154", "QA", "QAT"));
            lista.Add(new PaisesDanfe("1376", "Cayman, Ilhas", "137", "KY", "CYM"));
            lista.Add(new PaisesDanfe("1538", "Cazaquistão", "153", "KZ", "KAZ"));
            lista.Add(new PaisesDanfe("7889", "Chade", "788", "TD", "TCD"));
            lista.Add(new PaisesDanfe("1589", "Chile", "158", "CL", "CHL"));
            lista.Add(new PaisesDanfe("1600", "China", "160", "CN", "CHN"));
            lista.Add(new PaisesDanfe("1635", "Chipre", "163", "CY", "CYP"));
            lista.Add(new PaisesDanfe("5118", "Christmas (Navidad), Ilha", "511", "CX", "CXR"));
            lista.Add(new PaisesDanfe("7412", "Cingapura", "741", "SG", "SGP"));
            lista.Add(new PaisesDanfe("1651", "Cocos (Keeling), Ilhas", "165", "CC", "CCK"));
            lista.Add(new PaisesDanfe("1694", "Colômbia", "169", "CO", "COL"));
            lista.Add(new PaisesDanfe("1732", "Comores", "173", "KM", "COM"));
            lista.Add(new PaisesDanfe("1775", "Congo", "177", "CG", "COG"));
            lista.Add(new PaisesDanfe("1830", "Cook, Ilhas", "183", "CK", "COK"));
            lista.Add(new PaisesDanfe("1872", "Coreia do Norte", "187", "KP", "PRK"));
            lista.Add(new PaisesDanfe("1902", "Coreia do Sul", "190", "KR", "KOR"));
            lista.Add(new PaisesDanfe("1937", "Costa do Marfim", "193", "CI", "CIV"));
            lista.Add(new PaisesDanfe("1961", "Costa Rica", "196", "CR", "CRI"));
            lista.Add(new PaisesDanfe("1953", "Croácia", "195", "HR", "HRV"));
            lista.Add(new PaisesDanfe("1996", "Cuba", "199", "CU", "CUB"));
            lista.Add(new PaisesDanfe("2003", "Curaçao", "200", "CW", "CUW"));
            lista.Add(new PaisesDanfe("2321", "Dinamarca", "232", "DK", "DNK"));
            lista.Add(new PaisesDanfe("7838", "Djibuti", "783", "DJ", "DJI"));
            lista.Add(new PaisesDanfe("2356", "Dominica", "235", "DM", "DMA"));
            lista.Add(new PaisesDanfe("2402", "Egito", "240", "EG", "EGY"));
            lista.Add(new PaisesDanfe("6874", "El Salvador", "687", "SV", "SLV"));
            lista.Add(new PaisesDanfe("2445", "Emirados Árabes Unidos", "244", "AE", "ARE"));
            lista.Add(new PaisesDanfe("2399", "Equador", "239", "EC", "ECU"));
            lista.Add(new PaisesDanfe("2437", "Eritréia", "243", "ER", "ERI"));
            lista.Add(new PaisesDanfe("2470", "Eslováquia", "247", "SK", "SVK"));
            lista.Add(new PaisesDanfe("2461", "Eslovênia", "246", "SI", "SVN"));
            lista.Add(new PaisesDanfe("2453", "Espanha", "245", "ES", "ESP"));
            lista.Add(new PaisesDanfe("2496", "Estados Unidos", "249", "US", "USA"));
            lista.Add(new PaisesDanfe("2518", "Estônia", "251", "EE", "EST"));
            lista.Add(new PaisesDanfe("7544", "Eswatini (antiga Suazilândia)", "754", "SZ", "SWZ"));
            lista.Add(new PaisesDanfe("2534", "Etiópia", "253", "ET", "ETH"));
            lista.Add(new PaisesDanfe("2550", "Falkland (Malvinas)", "255", "FK", "FLK"));
            lista.Add(new PaisesDanfe("2593", "Faroe, Ilhas", "259", "FO", "FRO"));
            lista.Add(new PaisesDanfe("8702", "Fiji", "870", "FJ", "FJI"));
            lista.Add(new PaisesDanfe("2674", "Filipinas", "267", "PH", "PHL"));
            lista.Add(new PaisesDanfe("2712", "Finlândia", "271", "FI", "FIN"));
            lista.Add(new PaisesDanfe("2755", "França", "275", "FR", "FRA"));
            lista.Add(new PaisesDanfe("2810", "Gabão", "281", "GA", "GAB"));
            lista.Add(new PaisesDanfe("2852", "Gâmbia", "285", "GM", "GMB"));
            lista.Add(new PaisesDanfe("2895", "Gana", "289", "GH", "GHA"));
            lista.Add(new PaisesDanfe("2917", "Geórgia", "291", "GE", "GEO"));
            lista.Add(new PaisesDanfe("2933", "Gibraltar", "293", "GI", "GIB"));
            lista.Add(new PaisesDanfe("2976", "Granada", "297", "GD", "GRD"));
            lista.Add(new PaisesDanfe("3018", "Grécia", "301", "GR", "GRC"));
            lista.Add(new PaisesDanfe("3050", "Groenlândia", "305", "GL", "GRL"));
            lista.Add(new PaisesDanfe("3093", "Guadalupe", "309", "GP", "GLP"));
            lista.Add(new PaisesDanfe("3131", "Guam", "313", "GU", "GUM"));
            lista.Add(new PaisesDanfe("3174", "Guatemala", "317", "GT", "GTM"));
            lista.Add(new PaisesDanfe("1504", "Guernsey, Ilha do Canal (inclui Alderney e Sark)", "321", "GG", "GGY"));
            lista.Add(new PaisesDanfe("3379", "Guiana", "337", "GY", "GUY"));
            lista.Add(new PaisesDanfe("3255", "Guiana Francesa", "325", "GF", "GUF"));
            lista.Add(new PaisesDanfe("3298", "Guiné", "329", "GN", "GIN"));
            lista.Add(new PaisesDanfe("3344", "Guiné-Bissau", "334", "GW", "GNB"));
            lista.Add(new PaisesDanfe("3310", "Guiné Equatorial", "331", "GQ", "GNQ"));
            lista.Add(new PaisesDanfe("3417", "Haiti", "341", "HT", "HTI"));
            lista.Add(new PaisesDanfe("5738", "Países Baixos (Holanda)", "573", "NL", "NLD"));
            lista.Add(new PaisesDanfe("3450", "Honduras", "345", "HN", "HND"));
            lista.Add(new PaisesDanfe("3514", "Hong Kong", "351", "HK", "HKG"));
            lista.Add(new PaisesDanfe("3557", "Hungria", "355", "HU", "HUN"));
            lista.Add(new PaisesDanfe("3573", "Iêmen", "357", "YE", "YEM"));
            lista.Add(new PaisesDanfe("3611", "Índia", "361", "IN", "IND"));
            lista.Add(new PaisesDanfe("3654", "Indonésia", "365", "ID", "IDN"));
            lista.Add(new PaisesDanfe("3727", "Irã", "372", "IR", "IRN"));
            lista.Add(new PaisesDanfe("3697", "Iraque", "369", "IQ", "IRQ"));
            lista.Add(new PaisesDanfe("3751", "Irlanda", "375", "IE", "IRL"));
            lista.Add(new PaisesDanfe("3794", "Islândia", "379", "IS", "ISL"));
            lista.Add(new PaisesDanfe("3832", "Israel", "383", "IL", "ISR"));
            lista.Add(new PaisesDanfe("3867", "Itália", "386", "IT", "ITA"));
            lista.Add(new PaisesDanfe("3913", "Jamaica", "391", "JM", "JAM"));
            lista.Add(new PaisesDanfe("3999", "Japão", "399", "JP", "JPN"));
            lista.Add(new PaisesDanfe("1508", "Canal, Ilhas do (Jersey)", "393", "JE", "JEY"));
            lista.Add(new PaisesDanfe("3964", "Johnston, Ilhas", "396", "US", "USA"));
            lista.Add(new PaisesDanfe("4030", "Jordânia", "403", "JO", "JOR"));
            lista.Add(new PaisesDanfe("4111", "Kiribati", "411", "KI", "KIR"));
            lista.Add(new PaisesDanfe("1988", "Kuweit (Coveite)", "198", "KW", "KWT"));
            lista.Add(new PaisesDanfe("4200", "Laos", "420", "LA", "LAO"));
            lista.Add(new PaisesDanfe("4260", "Lesoto", "426", "LS", "LSO"));
            lista.Add(new PaisesDanfe("4278", "Letônia", "427", "LV", "LVA"));
            lista.Add(new PaisesDanfe("4316", "Líbano", "431", "LB", "LBN"));
            lista.Add(new PaisesDanfe("4340", "Libéria", "434", "LR", "LBR"));
            lista.Add(new PaisesDanfe("4383", "Líbia", "438", "LY", "LBY"));
            lista.Add(new PaisesDanfe("4405", "Liechtenstein", "440", "LI", "LIE"));
            lista.Add(new PaisesDanfe("4421", "Lituânia", "442", "LT", "LTU"));
            lista.Add(new PaisesDanfe("4456", "Luxemburgo", "445", "LU", "LUX"));
            lista.Add(new PaisesDanfe("4472", "Macau", "447", "MO", "MAC"));
            lista.Add(new PaisesDanfe("4421", "Macedônia", "449", "MK", "MKD"));
            lista.Add(new PaisesDanfe("4502", "Madagascar", "450", "MG", "MDG"));
            lista.Add(new PaisesDanfe("4525", "Madeira, Ilha da", "452", "PT", "PRT"));
            lista.Add(new PaisesDanfe("4553", "Malásia", "455", "MY", "MYS"));
            lista.Add(new PaisesDanfe("4588", "Malavi", "458", "MW", "MWI"));
            lista.Add(new PaisesDanfe("4618", "Maldivas", "461", "MV", "MDV"));
            lista.Add(new PaisesDanfe("4642", "Mali", "464", "ML", "MLI"));
            lista.Add(new PaisesDanfe("4677", "Malta", "467", "MT", "MLT"));
            lista.Add(new PaisesDanfe("3595", "Man, Ilha de", "359", "IM", "IMN"));
            lista.Add(new PaisesDanfe("4723", "Marianas do Norte, Ilhas", "472", "MP", "MNP"));
            lista.Add(new PaisesDanfe("4740", "Marrocos", "474", "MA", "MAR"));
            lista.Add(new PaisesDanfe("4766", "Marshall, Ilhas", "476", "MH", "MHL"));
            lista.Add(new PaisesDanfe("4774", "Martinica", "477", "MQ", "MTQ"));
            lista.Add(new PaisesDanfe("4855", "Maurício", "485", "MU", "MUS"));
            lista.Add(new PaisesDanfe("4880", "Mauritânia", "488", "MR", "MRT"));
            lista.Add(new PaisesDanfe("4936", "México", "493", "MX", "MEX"));
            lista.Add(new PaisesDanfe("0930", "Mianmar", "093", "MM", "MMR"));
            lista.Add(new PaisesDanfe("4995", "Micronésia", "499", "FS", "FSM"));
            lista.Add(new PaisesDanfe("4901", "Midway, Ilhas", "490", "UM", "UMI"));
            lista.Add(new PaisesDanfe("5053", "Moçambique", "505", "MZ", "MOZ"));
            lista.Add(new PaisesDanfe("4944", "Moldávia", "494", "MD", "MDA"));
            lista.Add(new PaisesDanfe("4952", "Mônaco", "495", "MC", "MCO"));
            lista.Add(new PaisesDanfe("4979", "Mongólia", "497", "MN", "MNG"));
            lista.Add(new PaisesDanfe("4985", "Montenegro", "498", "ME", "MNE"));
            lista.Add(new PaisesDanfe("5010", "Montserrat", "501", "MS", "MSR"));
            lista.Add(new PaisesDanfe("5070", "Namíbia", "507", "NA", "NAM"));
            lista.Add(new PaisesDanfe("5088", "Nauru", "508", "NR", "NRU"));
            lista.Add(new PaisesDanfe("5177", "Nepal", "517", "NP", "NPL"));
            lista.Add(new PaisesDanfe("5215", "Nicarágua", "521", "NI", "NIC"));
            lista.Add(new PaisesDanfe("5258", "Níger", "525", "NE", "NER"));
            lista.Add(new PaisesDanfe("5282", "Nigéria", "528", "NG", "NGA"));
            lista.Add(new PaisesDanfe("5312", "Niue", "531", "NU", "NIU"));
            lista.Add(new PaisesDanfe("5355", "Norfolk, Ilha", "535", "NF", "NFK"));
            lista.Add(new PaisesDanfe("5380", "Noruega", "538", "NO", "NOR"));
            lista.Add(new PaisesDanfe("5428", "Nova Caledônia", "542", "NC", "NCL"));
            lista.Add(new PaisesDanfe("5487", "Nova Zelândia", "548", "NZ", "NZL"));
            lista.Add(new PaisesDanfe("5568", "Omã", "556", "OM", "OMN"));
            lista.Add(new PaisesDanfe("5665", "Pacífico, Ilhas do (EUA)", "566", "UM", "UMI"));
            lista.Add(new PaisesDanfe("5754", "Palau", "575", "PW", "PLW"));
            lista.Add(new PaisesDanfe("5780", "Palestina", "578", "PS", "PSE"));
            lista.Add(new PaisesDanfe("5800", "Panamá", "580", "PA", "PAN"));
            lista.Add(new PaisesDanfe("5452", "Papua Nova Guiné", "545", "PG", "PNG"));
            lista.Add(new PaisesDanfe("5762", "Paquistão", "576", "PK", "PAK"));
            lista.Add(new PaisesDanfe("5860", "Paraguai", "586", "PY", "PRY"));
            lista.Add(new PaisesDanfe("5894", "Peru", "589", "PE", "PER"));
            lista.Add(new PaisesDanfe("5932", "Pitcairn", "593", "PN", "PCN"));
            lista.Add(new PaisesDanfe("5991", "Polinésia Francesa", "599", "PF", "PYF"));
            lista.Add(new PaisesDanfe("6033", "Polônia", "603", "PL", "POL"));
            lista.Add(new PaisesDanfe("6114", "Porto Rico", "611", "PR", "PRI"));
            lista.Add(new PaisesDanfe("6076", "Portugal", "607", "PT", "PRT"));
            lista.Add(new PaisesDanfe("6238", "Quênia", "623", "KE", "KEN"));
            lista.Add(new PaisesDanfe("6254", "Quirguistão", "625", "KG", "KGZ"));
            lista.Add(new PaisesDanfe("6289", "Reino Unido", "628", "GB", "GBR"));
            lista.Add(new PaisesDanfe("6408", "República Centro-Africana", "640", "CF", "CAF"));
            lista.Add(new PaisesDanfe("8885", "República Democrática do Congo", "888", "CD", "COD"));
            lista.Add(new PaisesDanfe("6475", "República Dominicana", "647", "DO", "DOM"));
            lista.Add(new PaisesDanfe("7919", "República Tcheca", "791", "CZ", "CZE"));
            lista.Add(new PaisesDanfe("6602", "Reunião", "660", "RE", "REU"));
            lista.Add(new PaisesDanfe("6700", "Romênia", "670", "RO", "ROU"));
            lista.Add(new PaisesDanfe("6750", "Ruanda", "675", "RW", "RWA"));
            lista.Add(new PaisesDanfe("6769", "Rússia", "676", "RU", "RUS"));
            lista.Add(new PaisesDanfe("6858", "Saara Ocidental", "685", "EH", "ESH"));
            lista.Add(new PaisesDanfe("6777", "Salomão, Ilhas", "677", "SB", "SLB"));
            lista.Add(new PaisesDanfe("6904", "Samoa", "690", "WS", "WSM"));
            lista.Add(new PaisesDanfe("6912", "Samoa Americana", "691", "AS", "ASM"));
            lista.Add(new PaisesDanfe("6971", "San Marino", "697", "SM", "SMR"));
            lista.Add(new PaisesDanfe("7102", "Santa Helena", "710", "SH", "SHN"));
            lista.Add(new PaisesDanfe("7153", "Santa Lúcia", "715", "LC", "LCA"));
            lista.Add(new PaisesDanfe("6955", "São Cristóvão e Névis", "695", "KN", "KNA"));
            lista.Add(new PaisesDanfe("6980", "São Martinho, ilha de (parte francesa)", "698", "MF", "MAF"));
            lista.Add(new PaisesDanfe("6998", "São Martinho, ilha de (parte holandesa)", "699", "SX", "SXM"));
            lista.Add(new PaisesDanfe("7005", "São Pedro e Miquelon", "700", "PM", "SPM"));
            lista.Add(new PaisesDanfe("7200", "São Tomé e Príncipe", "720", "ST", "STP"));
            lista.Add(new PaisesDanfe("7056", "São Vicente e Granadinas", "705", "VC", "VCT"));
            lista.Add(new PaisesDanfe("7315", "Seychelles", "731", "SC", "SYC"));
            lista.Add(new PaisesDanfe("7285", "Senegal", "728", "SN", "SEN"));
            lista.Add(new PaisesDanfe("7358", "Serra Leoa", "735", "SL", "SLE"));
            lista.Add(new PaisesDanfe("7370", "Sérvia", "737", "RS", "SRB"));
            lista.Add(new PaisesDanfe("7447", "Síria", "744", "SY", "SYR"));
            lista.Add(new PaisesDanfe("7480", "Somália", "748", "SO", "SOM"));
            lista.Add(new PaisesDanfe("7501", "Sri Lanka", "750", "LK", "LKA"));
            lista.Add(new PaisesDanfe("7595", "Sudão", "759", "SD", "SDN"));
            lista.Add(new PaisesDanfe("7600", "Sudão do Sul", "760", "SS", "SSD"));
            lista.Add(new PaisesDanfe("7641", "Suécia", "764", "SE", "SWE"));
            lista.Add(new PaisesDanfe("7676", "Suíça", "767", "CH", "CHE"));
            lista.Add(new PaisesDanfe("7706", "Suriname", "770", "SR", "SUR"));
            lista.Add(new PaisesDanfe("7552", "Svalbard e Jan Mayen", "755", "SJ", "SJM"));
            lista.Add(new PaisesDanfe("7722", "Tadjiquistão", "772", "TJ", "TJK"));
            lista.Add(new PaisesDanfe("7765", "Tailândia", "776", "TH", "THA"));
            lista.Add(new PaisesDanfe("1619", "Taiwan (Formosa)", "161", "TW", "TWN"));
            lista.Add(new PaisesDanfe("7803", "Tanzânia", "780", "TZ", "TZA"));
            lista.Add(new PaisesDanfe("7820", "Território Britânico do Oceano Índico", "782", "IO", "IOT"));
            lista.Add(new PaisesDanfe("7951", "Timor Leste", "795", "TP", "TLS"));
            lista.Add(new PaisesDanfe("8001", "Togo", "800", "TG", "TGO"));
            lista.Add(new PaisesDanfe("8109", "Tonga", "810", "TO", "TON"));
            lista.Add(new PaisesDanfe("8052", "Toquelau", "805", "TK", "TKL"));
            lista.Add(new PaisesDanfe("8150", "Trinidad e Tobago", "815", "TT", "TTO"));
            lista.Add(new PaisesDanfe("8206", "Tunísia", "820", "TN", "TUN"));
            lista.Add(new PaisesDanfe("8230", "Turcas e Caicos, Ilhas", "823", "TC", "TCA"));
            lista.Add(new PaisesDanfe("8249", "Turcomenistão", "824", "TM", "TKM"));
            lista.Add(new PaisesDanfe("8273", "Turquia", "827", "TR", "TUR"));
            lista.Add(new PaisesDanfe("8281", "Tuvalu", "828", "TV", "TUV"));
            lista.Add(new PaisesDanfe("8311", "Ucrânia", "831", "UA", "UKR"));
            lista.Add(new PaisesDanfe("8338", "Uganda", "833", "UG", "UGA"));
            lista.Add(new PaisesDanfe("8451", "Uruguai", "845", "UY", "URY"));
            lista.Add(new PaisesDanfe("8478", "Uzbequistão", "847", "UZ", "UZB"));
            lista.Add(new PaisesDanfe("5517", "Vanuatu", "551", "VU", "VUT"));
            lista.Add(new PaisesDanfe("8486", "Vaticano", "848", "VA", "VAT"));
            lista.Add(new PaisesDanfe("8508", "Venezuela", "850", "VE", "VEN"));
            lista.Add(new PaisesDanfe("8583", "Vietnã", "858", "VN", "VNM"));
            lista.Add(new PaisesDanfe("8630", "Virgens, Ilhas (Britânicas)", "863", "VG", "VGB"));
            lista.Add(new PaisesDanfe("8664", "Virgens, Ilhas (Americanas)", "866", "VI", "VIR"));
            lista.Add(new PaisesDanfe("8737", "Wake, Ilha", "873", "US", "USA"));
            lista.Add(new PaisesDanfe("8753", "Wallis e Futuna, Ilhas", "875", "WF", "WLF"));
            lista.Add(new PaisesDanfe("8907", "Zâmbia", "890", "ZM", "ZMB"));
            lista.Add(new PaisesDanfe("6653", "Zimbábue", "665", "ZW", "ZWE"));

            return lista;
        }
    }
}